# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: builded_image:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: si
      MARIADB_ROOT_PASSWORD_HASH:
      MARIADB_RANDOM_ROOT_PASSWORD:

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080